const bgByType = {
    normal: "bg-gradient-to-t from-pink-600 to-pink-900",
    fighting: "bg-gradient-to-t from-red-500 to-red-900",
    flying: "bg-gradient-to-t from-yellow-400 to-yellow-600",
    poison: "bg-gradient-to-t from-purple-500 to-purple-900",
    ground: "bg-gradient-to-t from-amber-800 to-amber-950",
    rock: "bg-gradient-to-t from-slate-200 to-slate-400",
    bug: "bg-gradient-to-t from-green-200 to-green-500",
    ghost: "bg-gradient-to-t from-blue-900 to-blue-950",
    steel: "bg-gradient-to-t from-gray-400 to-gray-600",
    fire: "bg-gradient-to-t from-orange-500 to-orange-700",
    water: "bg-gradient-to-t from-blue-400 to-blue-700",
    grass: "bg-gradient-to-t from-green-300 to-cyan-400",
    electric: "bg-gradient-to-t from-indigo-800 to-indigo-950",
    psychic: "bg-gradient-to-t from-gray-800 to-gray-950",
    ice: "bg-gradient-to-t from-cyan-200 to-cyan-300",
    dragon: "bg-gradient-to-t from-blue-300 to-blue-400",
    dark: "bg-gradient-to-t from-slate-800 to-slate-950",
    fairy: "bg-gradient-to-t from-pink-400 to-pink-500",
    unknown: "",
    shadow: "",
  };

  const borderByType = {
    normal: "border-pink-900",
    fighting: "border-red-900/90",
    flying: "border-yellow-600",
    poison: "border-purple-900",
    ground: "border-amber-950",
    rock: "border-slate-400",
    bug: "border-green-400",
    ghost: "border-blue-950",
    steel: "border-gray-600",
    fire: "border-orange-700",
    water: "border-blue-700",
    grass: "border-cyan-400",
    electric: "border-indigo-950",
    psychic: "border-gray-950",
    ice: "border-cyan-300",
    dragon: "border-blue-400",
    dark: "border-slate-950",
    fairy: "border-pink-500",
    unknown: "",
    shadow: "",
  };

  const textByType = {
    normal: "text-pink-900",
    fighting: "text-red-900/90",
    flying: "text-yellow-600",
    poison: "text-purple-900",
    ground: "text-amber-950",
    rock: "text-slate-400",
    bug: "text-green-400",
    ghost: "text-blue-950",
    steel: "text-gray-600",
    fire: "text-orange-700",
    water: "text-blue-700",
    grass: "text-cyan-400",
    electric: "text-indigo-950",
    psychic: "text-gray-950",
    ice: "text-cyan-300",
    dragon: "text-blue-400",
    dark: "text-slate-950",
    fairy: "text-pink-500",
    unknown: "",
    shadow: "",
  };
  
  export { bgByType, borderByType, textByType };